return {
    -- {"linux-cultist/venv-selector.nvim",
    --     dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim", 
    --         "mfussenegger/nvim-dap-python","nvim-lua/plenary.nvim" },
    --     config = function()
    --         require("venv-selector").setup({
    --             fd_binary_name = "find",
    --             anaconda_base_path = "/opt/homebrew/Caskroom/miniconda/base",
    --             anaconda_envs_path = "/opt/homebrew/Caskroom/miniconda/base/envs",
    --
    --         })
    --     end,
    --     event = "VeryLazy", -- Optional: needed only if you want to type `:VenvSelect` without a keymapping
    --     keys = {{ "<leader>vs", "<cmd>VenvSelect<cr>" },}
    -- },
    -- {"GCBallesteros/NotebookNavigator.nvim",
    --     keys = {
    --         { "]h", function() require("notebook-navigator").move_cell "d" end },
    --         { "[h", function() require("notebook-navigator").move_cell "u" end },
    --         { "<leader>X", "<cmd>lua require('notebook-navigator').run_cell()<cr>" },
    --         { "<leader>x", "<cmd>lua require('notebook-navigator').run_and_move()<cr>" },
    --     },
    --     dependencies = {
    --         "echasnovski/mini.comment",
    --         "hkupty/iron.nvim", -- repl provider
    --         -- "akinsho/toggleterm.nvim", -- alternative repl provider
    --         "anuvyklack/hydra.nvim",
    --     },
    --     event = "VeryLazy",
    --     config = function()
    --         local nn = require "notebook-navigator"
    --         nn.setup({ activate_hydra_keys = "<leader>h" })
    --     end,
    -- }
}
